FROM ghcr.io/autowarefoundation/autoware:universe-devel-cuda-1.7.1-jazzy-amd64

# Download necessary packages
RUN apt-get update
# Useful tools
RUN apt-get install -y wget unzip tmux inetutils-ping curl vim parallel
RUN printf 'set-option -g default-shell /bin/bash\nset -g default-terminal "tmux-256color"' > /etc/tmux.conf
# Used by zenoh-bridge-ros2dds
RUN apt-get install -y llvm-dev libclang-dev cmake
# Used by Autoware & my ROS packages
RUN python3 -m pip install --break-system-packages gdown
RUN apt-get install -y ros-jazzy-moveit-msgs \
                       ros-jazzy-object-recognition-msgs \
                       ros-jazzy-octomap-msgs \
                       ros-jazzy-rviz-2d-overlay-plugins

CMD bash
